/*****************************************************************************  
    Copyright (c) My Company

    Project:  TETRISV2  
    FileName: TETRISV2.PRO  
    Purpose:  No description  
    Written by: Visual Prolog  
    Comments:
******************************************************************************/

/*****************************************************************************
User's Declarations
*****************************************************************************/
global domains
  DB_SELECTOR = browselist_db% For treebrowser tool
  FILE = fileselector1; fileselector2 % To be edited